---
- name: Create Minio namespace
  block:
    - copy: src=minio-namespace.yaml dest=/tmp/minio-namespace.yaml
    - command: kubectl apply -f /tmp/minio-namespace.yaml

- name: Create self-signed certs and secret
  block:
  - command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout minio-private.key -out minio-public.crt -subj "/CN=kubeserver/O=kubeserver"
  - command: kubectl create secret generic tls-ssl-minio --from-file=private.key=minio-private.key --from-file=public.crt=minio-public.crt --namespace=minio
  when: enable_tls == true

- name: Create Persistent Volume Claim
  block:
    - template: src=minio-standalone-pvc.j2 dest=/tmp/minio-standalone-pvc.yaml
    - command: kubectl apply -f /tmp/minio-standalone-pvc.yaml

- include: minio-notifications.yaml
  when: enable_notifications == true

- include: minio.yaml
  when: enable_notifications == false

- name: Create Service
  block:
    - copy: src=minio-standalone-service.yaml dest=/tmp/minio-standalone-service.yaml
    - command: kubectl apply -f /tmp/minio-standalone-service.yaml

- name: Download Minio Client binary
  get_url:
    url: https://dl.minio.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin/mc
    mode: 0755