---
- name: Create Minio namespace
  block:
    - copy: src=minio-namespace.yaml dest=/tmp/minio-namespace.yaml
    - command: kubectl apply -f /tmp/minio-namespace.yaml

- name: Create Persistent Volume Claim
  block:
    - template: src=minio-standalone-pvc.j2 dest=/tmp/minio-standalone-pvc.yaml
    - command: kubectl apply -f /tmp/minio-standalone-pvc.yaml

- include: minio-notifications.yaml
  when: enable_notifications == true

- include: minio.yaml
  when: enable_notifications == false

- name: Create Service
  block:
    - copy: src=minio-standalone-service.yaml dest=/tmp/minio-standalone-service.yaml
    - command: kubectl apply -f /tmp/minio-standalone-service.yaml

- name: Download Minio Client binary
  get_url:
    url: https://dl.minio.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin/mc
    mode: 0755