---
- name: Create Minio namespace
  block:
    - copy: src=minio-namespace.yaml dest=/tmp/minio-namespace.yaml
    - command: kubectl apply -f /tmp/minio-namespace.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"


- name: TLS support
  block:
  - name: Check if certs are created
    block:
    - stat:
        path: /var/tmp/certs
      register: certs_dir
    - stat:
        path: /var/tmp/certs/private.key
      register: certs_private
    - stat:
        path: /var/tmp/certs/public.crt
      register: certs_public
  - name: Create certs dir
    command: mkdir /var/tmp/certs
    when: not certs_dir.stat.exists
  - name: Create certs
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /var/tmp/certs/private.key -out /var/tmp/certs/public.crt -subj "/CN=kubeserver/O=kubeserver"
    when: (not certs_private.stat.exists) or (not certs_public.stat.exists)
  - name: Check if tls-ssl-minio secret is created
    command: kubectl get secret certs -n minio
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"
    register: minio_secret_created
    failed_when: minio_secret_created.rc != 0 and minio_secret_created.rc != 1
  - name: Create certs secret
    command: kubectl create secret generic certs --from-file=/var/tmp/certs/private.key --from-file=/var/tmp/certs/public.crt --namespace minio
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"
    when: minio_secret_created.rc == 1
  when: enable_tls == true and enable_ingress != false

- name: Create Persistent Volume Claim
  block:
    - template: src=minio-standalone-pvc.j2 dest=/tmp/minio-standalone-pvc.yaml
    - command: kubectl apply -f /tmp/minio-standalone-pvc.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

- include: minio-notifications.yaml
  when: enable_notifications == true
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- include: minio.yaml
  when: enable_notifications == false
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

- name: Create Service
  block:
    - copy: src=minio-standalone-service.yaml dest=/tmp/minio-standalone-service.yaml
    - command: kubectl apply -f /tmp/minio-standalone-service.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

- name: Create Ingress
  block:
    - template: src=minio-ingress.j2 dest=/tmp/minio-ingress.yaml
    - command: kubectl apply -f /tmp/minio-ingress.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
  when: enable_ingress == true

- name: Download Minio Client binary
  get_url:
    url: https://dl.minio.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin/mc
    mode: 0755
