- name: Create standalone deployment
  block:
    - template: src=minio-standalone-deployment.j2 dest=/tmp/minio-standalone-deployment.yaml
    - command: kubectl apply -f /tmp/minio-standalone-deployment.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
