- name: Create configMap to enable webhooks notifications
  block:
    - template: src=minio-configmap-notifications.j2 dest=/tmp/minio-configmap-notifications.yaml
    - command: kubectl apply -f /tmp/minio-configmap-notifications.yaml

- name: Create standalone deployment loading the configMap
  block:
    - copy: src=minio-standalone-deployment-with-notifications.yaml dest=/tmp/minio-standalone-deployment-with-notifications.yaml
    - command: kubectl apply -f /tmp/minio-standalone-deployment-with-notifications.yaml