- name: Create configMap to enable webhooks notifications
  block:
    - copy: src=minio-configmap-notifications.yaml dest=/tmp/minio-configmap-notifications.yaml
    - replace:
        path: /tmp/minio-configmap-notifications.yaml
        regexp: 'webhook_endpoint'
        replace: '{{ webhook_endpoint }}'
    - command: kubectl create -f /tmp/minio-configmap-notifications.yaml

- name: Create standalone deployment loading the configMap
  block:
    - copy: src=minio-standalone-deployment-with-notifications.yaml dest=/tmp/minio-standalone-deployment-with-notifications.yaml
    - command: kubectl create -f /tmp/minio-standalone-deployment-with-notifications.yaml