apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
